apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-billing-service
  namespace: aurora
data:
  appsettings.json: |
    {
        "Serilog": {
          "MinimumLevel": {
            "Default": "Information",
            "Override": {
              "Microsoft": "Warning",
              "Microsoft.AspNetCore": "Warning"
            }          
    }
