apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-invoice-test
  namespace: aurora  
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: aurora-invoice-test
      app.kubernetes.io/name: aurora-invoice-test
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: aurora-invoice-test
        app.kubernetes.io/name: aurora-invoice-test
    spec:      
      containers:
        - name: aurora-invoice-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
        product: onepay
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
